name: GitHub Metrics

on:
  schedule:
    # Runs every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggering
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/metrics.yml"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Kolkata
          repositories_forks: true
          repositories_affiliations: owner, collaborator, organization_member
          repositories_skipped: ""

          # Display stats
          plugin_lines: yes
          plugin_traffic: yes

          # Display most used languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_threshold: 0%

          # Display isometric calendar (365 days)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Display recent activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all

          # Display achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C

          # Display contributions
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_notable_repositories: yes

          # Display recently starred repositories
          plugin_stars: yes
          plugin_stars_limit: 4

          # Display followers
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 24
          plugin_people_size: 28

          outputs: |
            github-metrics.svg
            metrics/*.svg
